language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install setuptools --upgrade
  - python bootstrap.py
  - bin/buildout
script: bin/py.test js/bootstrap/test_bootstrap.txt
